// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AUTH_SECRET: string;
	AUTH_GITHUB_ID: string;
	AUTH_GITHUB_SECRET: string;
	AUTH_WECHAT_APP_ID: string;
	AUTH_WECHAT_APP_SECRET: string;
	DATABASE_URL: string;
	DIRECT_DATABASE_URL: string;
}
